### PR TITLE
Company list alphabetically sorted (case insensitive)

### PR DESCRIPTION
**Pull request by shivaenigma**

### CODE REVIEW

**Comment by nvk-uasf** [comment]
Do you mind fixing the merge conflicts? 👍

**Comment by shivaenigma** [comment]
I can but you have to stop accepting other pull requests for companies... until this gets merged in. Otherwise it will continue to conflict

**Comment by nvk-uasf** [comment]
It wont stop, maybe fix this once, and next time people submit I will ask them to put in the right order.

**Comment by shivaenigma** [comment]
Fixing in 5 minutes.. Please dont accept other pull requests in between

**Comment by shivaenigma** [comment]
Done. Closed this ... opened new one having the updated list

**Pull request closed without merging**
