### PR TITLE
Update README.md: Add section "How can I run or re-compile bitcoind with UASF BIP148?"

### PR DESCRIPTION
**Pull request by EagleTM**
Add section: How can I run or re-compile bitcoind with UASF BIP148?

### CODE REVIEW

**Comment by nvk-uasf** [comment]
Not yet

**Comment by alp-bitcoin** [comment]
I think it can make sense to explain why running the binaries should not be done until there is widespread support.

**Comment by alp-bitcoin** [comment]
I added a change to discourage running binaries until there is sufficient consensus.

**Comment by EagleTM** [comment]
@alp-bitcoin: Thx

I'll close this for now because it's outdated again with v0.3
I'll try to keep my branch updated and you can pull things in if required

**Pull request closed without merging**
