### PR TITLE
Remove chart url

### PR DESCRIPTION
**Pull request by cypherblock**
Luke's charts show ever increasing node count from 37k total nodes on 3/18 up to 75k nodes on 4/10. Since this is unlikely to be accurate suggest we remove links to those charts for now.

### CODE REVIEW

**Comment by mkwia** [comment]
I would like @luke-jr to comment on his confidence in the accuracy of the data.

**Comment by luke-jr** [comment]
I'm suspicious of it, but I don't see any error in the math or measurements. Furthermore, while its counts continue to grow significantly, they seem mostly in line with growth in more reliable metrics.

Trusted Perl-comprehending people are welcome to review the code.

**Comment by cypherblock** [comment]
maybe you can just describe the technique that you use instead of sharing the code. Like are you using multiple globally placed nodes to gather stats from and capturing all IP addresses that connect to those nodes over a 24 hour period? Or what?

**Comment by cypherblock** [comment]
@alp-bitcoin I see you closed the pull request without any discussion on your part. I guess you stand by Luke's numbers even though there has been no good explanation for jump of 40k nodes in a month on luke's charts but no similar jump elsewhere. It is great we have so many more nodes, if they are real :)

**Pull request closed without merging**
